### ISSUE TITLE
File descriptor leak

### ISSUE THREAD

**Issue by Waitak** [lpereira/hardinfo#17]
When running on Ubuntu 14.04, hardinfo eventually stops updating due to too many open file descriptors when running as root, with the Sensors tab selected:

> (hardinfo:7211): Gtk-WARNING **: Error loading theme icon 'view-refresh' for stock: Error opening file: Too many open files

Terminating the process and restarting fixes the problem (temporarily). Also (and not necessarily related) the temperatures shown are temp1, temp2, temp3, temp4, temp5, temp6, temp7, temp1, temp2 and temp3. The duplicate values have the same temperature listed as the first occurrence of the same key.

**Comment by mckaygerhard** [comment]
this issue must be closed, they are two issues here, duplicate values of temperature are knowed to recent kernels, and file descriptor gtk problem are related to winbuntu integration (too many includes)

this issue must be closed due not responses from the author

**Comment by mckaygerhard** [comment]
this issue was invalid, i discovered its inherent to winbutu gtk style.. 
a) choose a gtk2 only env and use gtk flat-ruin or simple: no problem event i open several instances of
b) choose a gtk2/gtk3 heavy style in winbuntu, with a heavy icon theme.. problems happened

this issue must be closed, they are two issues here, duplicate values of temperature are knowed to recent kernels, and file descriptor gtk problem are related to winbuntu integration (too many includes)

this issue must be closed as invalid

**Comment by bp0** [comment]
Please see #163.
