### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by splace** [lpereira/hardinfo#26]
occurs when looking at 'input devices'.

also; usb devices and sensors display nothing.

and; going to 'operating system' reports; 'sh: 1: /lib/libc.so.6: not found'

Ubuntu mate 15.10, hardinfo installed from repo's

**Comment by mckaygerhard** [comment]
this are a problem of the mantainer, the hardinfo must be recompiled with the proper path for libs, due since multiarch the paths changed!

the problem its the winbuntu package i think! change to debian

if u download, compile,  instaled and started the local compilation (not the winbuntu package) and problem persist, then its a bug!

**Comment by splace** [comment]
OK, the crash caused some sort of watchdog app. to fire off a report, which hopefully will make them aware.

**Comment by lpereira** [comment]
Most of the crashes reported by the Ubuntu bug tracker happens in the (very old) version 0.5.1, and have been long fixed in the version available in this repository.  Unfortunately I'm not sure if a new release will be made soon, but you're always free to build it from source.

**Comment by mckaygerhard** [comment]
i'll made some dpkg work and then try to promote to debian as NMU

**Comment by bp0** [comment]
Please see #163.
