### ISSUE TITLE
Benchmark results for current machine should be styled differently

### ISSUE THREAD

**Issue by lpereira** [lpereira/hardinfo#516]
Maybe we can leverage the same stuff added for vendor tags to show a "This Machine" tag in the benchmark results?

**Comment by bp0** [comment]
Yeah would be pretty easy I'll look at it tonight.

**Comment by bp0** [comment]
Using something like `format_with_ansi_color(" This Machine ", "0;30;43", params.fmt_opts)` is easy, but the problem is #509, it can't (currently) be used on the key side of the shell key/value pair. 
I was thinking that the whole line is highlighted yellow in the HTML report, so maybe the shell could just highlight the whole row with the select/highlight flag as well.

**Comment by lpereira** [comment]
Fixed.
