### ISSUE TITLE
Storage device in the overview, have text missaligned

### ISSUE THREAD

**Issue by baryluk** [lpereira/hardinfo#601]
git master @ a72881a1d25b2b1ea7718c5e2f76b92ee43d8ef8

`-DHARDINFO_GTK3=1` enabled.

![Screenshot at 2021-02-21 12-57-45](https://user-images.githubusercontent.com/110322/108625753-800f0c00-7444-11eb-8805-6aa320016509.png)

As you can see, the first line of storage devices, is aligned differently than subsequent lines.

**Comment by lpereira** [comment]
It happens on my computer, too:
![Screenshot from 2021-02-21 11-30-38](https://user-images.githubusercontent.com/15001/108636135-4c030d80-747b-11eb-84a3-4480e4269745.png)

It's not the only problem in this pane, and that's why I'm considering throwing it away and using the normal panes for the summary view.  I just haven't gotten around moving things around.

**Comment by mckaygerhard** [comment]
well its not serious.. so i dont see why must be removed XD

**Comment by lpereira** [comment]
It's not just the text alignment. That can be fixed. There are a lot of
other things that are a problem with that thing.
