### ISSUE TITLE
Add keywords to hardinfo.desktop

### ISSUE THREAD

**Issue by tsimonq2** [lpereira/hardinfo#71]
In Debian, the Lintian tool is warning us about the hardinfo.desktop file lacking keywords. Documentation for doing this is [here](https://wiki.gnome.org/Initiatives/GnomeGoals/DesktopFileKeywords).

Is this something that can be added?

**Comment by mckaygerhard** [comment]
i cannot see it here https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html

either here: https://specifications.freedesktop.org/desktop-entry-spec/latest/apa.html

these things that you pointed are Gnome-shell specific! please take care of mor important things..  seems you are a user of gnomepuach..

have you see the many things that are missing respect the other desktop? its the gnomepuach desktop more important rather than WindowMaker? oh yeah WM are no so use in that dais, its that?

as i response in other issue, take care of important thing in debian packagin... please.. that wil be help more ....

**Comment by tsimonq2** [comment]
@mckaygerhard Please keep this thread on-topic as you are diverging from the original point. No, I don't use GNOME Shell, in fact, I use LXQt. It's just an automated tool that the Debian packagers use to ensure the packages follow all of Debian's policies.

Additionally, this is **not** just something GNOME Shell users will benefit from. This is something that makes it easier to classify the package.

@lpereira Is this something you would be interested in having in HardInfo?

**Comment by lpereira** [comment]
Sure. If you send a pull request I'll gladly merge it.

**Comment by mckaygerhard** [comment]
well make a edit in the github, then when save.. will ask to you to make a pull.. the rest will be done by lpereira

**Comment by tsimonq2** [comment]
@mckaygerhard I don't need you to tell me how to use GitHub.

**Comment by bp0** [comment]
@tsimonq2  PR #116 
The link you gave mentions adding `_` to `Keywords` to mark it for translation, but I'm not sure I understand how it works. Is it done by GNOME or are we supposed to do it? I just used `Keywords` without the `_` because that's how all of the .desktop files I find use it.

**Comment by mckaygerhard** [comment]
i guess i said that before.. there's other methods to translations process maybe a file merge method like qt does!
